### ISSUE TITLE
Project name misspelled(?)

### ISSUE THREAD

**Issue by Grimler91** [trihedral/AdruinoLatexListing#3]
Hi,

I found this repository through https://tex.stackexchange.com/questions/211415/how-to-set-up-listings-for-use-code-from-arduino. Nice work, and thanks for sharing, it works great. 

I noticed that the project name is misspelled (Adruino instead of Arduino), and I guess this might make it harder for people to find it. 

Have you considered renaming it?

**Comment by trihedral** [comment]
Wow, I've been glancing at this repo off and on for like a year - I can't believe I never noticed this.  Thanks a lot for pointing it out, I'll fix it right away!

**Comment by Grimler91** [comment]
The README header is spelled the same way as well. 
Glad to be able to help!
